apiVersion: apps/v1
kind: Deployment
metadata:
  name: boundedcontext3293827160493827
  labels:
    app: boundedcontext3293827160493827
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boundedcontext3293827160493827
  template:
    metadata:
      labels:
        app: boundedcontext3293827160493827
    spec:
      containers:
        - name: boundedcontext3293827160493827
          image: "username/boundedcontext3293827160493827:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
