apiVersion: apps/v1
kind: Deployment
metadata:
  name: boundedcontext3516049382716049
  labels:
    app: boundedcontext3516049382716049
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boundedcontext3516049382716049
  template:
    metadata:
      labels:
        app: boundedcontext3516049382716049
    spec:
      containers:
        - name: boundedcontext3516049382716049
          image: "username/boundedcontext3516049382716049:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
