apiVersion: v1
kind: Service
metadata:
  name: boundedcontext3516049382716049
  labels:
    app: boundedcontext3516049382716049
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: boundedcontext3516049382716049