apiVersion: apps/v1
kind: Deployment
metadata:
  name: attachment
  labels:
    app: attachment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attachment
  template:
    metadata:
      labels:
        app: attachment
    spec:
      containers:
        - name: attachment
          image: "username/attachment:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
